---
title: "Resume"
output: html_document
---

[.pdf version](Mangin Resume.pdf)

## Work Experience

### Director of Research
Comlinkdata
July 2021 to Present

* Developed modeling and oversaw implementation for a full upgrade of Comlinkdata’s flagship data product, ensuring key contract extensions and upselling for largest
clients

### Economist
Comlinkdata
July 2016 to July 2021

* Developed and deployed a full-industry-view model for Wireless and Device markets, integrating multiple points
of internal and external information within a framework of constantly-updating Bayesian inference

* Expanded forecasting offerings and improved data and modelling quality, driving growth in a underdeveloped industry vertical


### Senior Analyst
Comlinkdata
July 2016 to July 2017 

* Developed and drove revenue growth from a novel digital audiences product based on individual-level model of
consumer demand

* Utilized and developed big data architecture for forecasting and estimation tasks utilizing R, Hive, Spark, and AWS ecosystem

### Instructor
University of Colorado
August 2014 to May 2016

* Taught four semester-length introductory lecture sections of between 150-250 students each
* Above average scores on student Faculty Course Questionnaires


### Accounting Intern
Whole Foods
February 2012 to July 2013

* Created ARMIA sales forecasting modelsfor regional store and department level weekly sales
* Organized and streamlined process of cost-discrepancy resolution

### Produce Buyer
Whole Foods
March 2009 to February 2012

• Purchased and maintained inventory for roughly /$10 million per year of fresh produce
• Created novel sales-modeling and automated inventory tracking, leading to a 10% reduction in spoilage and waste


## Education

### PhD  
Economics (May 2019)
The University of Colorado


### Master of Arts 
Economics (May 2014)
The University of Colorado

### Bachelor of Arts
History (May 2008)
The University of Colorado



## Research

Graduate Award for Public Policy Research The University of Colorado Economics (2016)

"USDA Organic Labels and Nutritional Quality" 
* Presented at 2016 Summer Conference of the Association of Environmental and Resource Economists 

"Salience of Promotional Prices with In-Store Advertising"

"Learning Costs and Peer Effects in Mobile Phone Service Provision"

## Computer Skills 

Basic 

* AWS (EC2, EMR, S3, Athena)
* Hive/HQ
* Bash
* Spark (scala, sparkR) 
* git 
* Python 

Advanced 

* Stan
* STATA 
* SQL (Microsoft, PostgresSQL)
* R (data.table, markdown)
* STAN (rstan)


